-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accommodation_types
(
    type_id serial NOT NULL,
    type_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    type_description text COLLATE pg_catalog."default",
    comfort_level integer,
    CONSTRAINT accommodation_types_pkey PRIMARY KEY (type_id),
    CONSTRAINT accommodation_types_type_name_key UNIQUE (type_name)
);

CREATE TABLE IF NOT EXISTS public.accommodations
(
    accommodation_id serial NOT NULL,
    accommodation_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    type_id integer,
    park_id integer,
    location text COLLATE pg_catalog."default",
    accommodation_description text COLLATE pg_catalog."default",
    amenities text[] COLLATE pg_catalog."default",
    room_types text[] COLLATE pg_catalog."default",
    rating numeric(2, 1),
    image_urls text[] COLLATE pg_catalog."default",
    contact_email character varying(255) COLLATE pg_catalog."default",
    contact_phone character varying(20) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT accommodations_pkey PRIMARY KEY (accommodation_id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    log_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    action_performed character varying(100) COLLATE pg_catalog."default" NOT NULL,
    entity_type character varying(50) COLLATE pg_catalog."default",
    entity_id character varying(100) COLLATE pg_catalog."default",
    old_values jsonb,
    new_values jsonb,
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (log_id)
);

COMMENT ON TABLE public.audit_logs
    IS 'Security audit trail for compliance and monitoring.';

CREATE TABLE IF NOT EXISTS public.blog_categories
(
    category_id serial NOT NULL,
    category_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category_slug character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category_description text COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    CONSTRAINT blog_categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT blog_categories_category_name_key UNIQUE (category_name),
    CONSTRAINT blog_categories_category_slug_key UNIQUE (category_slug)
);

CREATE TABLE IF NOT EXISTS public.blog_posts
(
    post_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    post_title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    post_slug character varying(200) COLLATE pg_catalog."default" NOT NULL,
    post_excerpt text COLLATE pg_catalog."default",
    post_content text COLLATE pg_catalog."default" NOT NULL,
    author_id uuid,
    category_id integer,
    featured_image_url text COLLATE pg_catalog."default",
    post_tags text[] COLLATE pg_catalog."default",
    meta_title character varying(200) COLLATE pg_catalog."default",
    meta_description text COLLATE pg_catalog."default",
    is_published boolean DEFAULT false,
    published_at timestamp without time zone,
    views_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT blog_posts_pkey PRIMARY KEY (post_id),
    CONSTRAINT blog_posts_post_slug_key UNIQUE (post_slug)
);

CREATE TABLE IF NOT EXISTS public.booking_statuses
(
    status_id serial NOT NULL,
    status_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    status_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status_description text COLLATE pg_catalog."default",
    display_order integer DEFAULT 0,
    CONSTRAINT booking_statuses_pkey PRIMARY KEY (status_id),
    CONSTRAINT booking_statuses_status_code_key UNIQUE (status_code)
);

CREATE TABLE IF NOT EXISTS public.booking_travelers
(
    traveler_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    booking_id uuid,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default",
    phone character varying(20) COLLATE pg_catalog."default",
    nationality character varying(100) COLLATE pg_catalog."default",
    passport_number character varying(50) COLLATE pg_catalog."default",
    passport_expiry date,
    date_of_birth date,
    emergency_contact_name character varying(200) COLLATE pg_catalog."default",
    emergency_contact_phone character varying(20) COLLATE pg_catalog."default",
    is_primary_contact boolean DEFAULT false,
    CONSTRAINT booking_travelers_pkey PRIMARY KEY (traveler_id)
);

CREATE TABLE IF NOT EXISTS public.bookings
(
    booking_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    booking_reference character varying(20) COLLATE pg_catalog."default" NOT NULL,
    user_id uuid,
    package_id uuid,
    booking_date date NOT NULL DEFAULT CURRENT_DATE,
    start_date date NOT NULL,
    end_date date NOT NULL,
    number_of_adults integer NOT NULL DEFAULT 1,
    number_of_children integer DEFAULT 0,
    children_ages integer[],
    total_price_usd numeric(10, 2) NOT NULL,
    special_requests text COLLATE pg_catalog."default",
    dietary_restrictions text COLLATE pg_catalog."default",
    medical_conditions text COLLATE pg_catalog."default",
    status_id integer DEFAULT 1,
    booking_source character varying(50) COLLATE pg_catalog."default",
    assigned_guide_id uuid,
    assigned_vehicle_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bookings_pkey PRIMARY KEY (booking_id),
    CONSTRAINT bookings_booking_reference_key UNIQUE (booking_reference)
);

COMMENT ON TABLE public.bookings
    IS 'Main bookings table with all reservation details. No payment information stored.';

COMMENT ON COLUMN public.bookings.total_price_usd
    IS 'Total booking amount in USD for reference only.';

CREATE TABLE IF NOT EXISTS public.conservation_areas
(
    area_id serial NOT NULL,
    area_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    park_id integer,
    area_description text COLLATE pg_catalog."default",
    special_features text COLLATE pg_catalog."default",
    image_urls text[] COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    CONSTRAINT conservation_areas_pkey PRIMARY KEY (area_id),
    CONSTRAINT conservation_areas_area_name_key UNIQUE (area_name)
);

CREATE TABLE IF NOT EXISTS public.contact_enquiries
(
    enquiry_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    full_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    country character varying(100) COLLATE pg_catalog."default",
    enquiry_type character varying(50) COLLATE pg_catalog."default",
    package_id uuid,
    preferred_travel_date date,
    number_of_travelers integer,
    enquiry_message text COLLATE pg_catalog."default" NOT NULL,
    ip_address inet,
    enquiry_status character varying(20) COLLATE pg_catalog."default" DEFAULT 'New'::character varying,
    assigned_to uuid,
    response_notes text COLLATE pg_catalog."default",
    responded_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT contact_enquiries_pkey PRIMARY KEY (enquiry_id)
);

CREATE TABLE IF NOT EXISTS public.countries
(
    country_id serial NOT NULL,
    country_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    country_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    phone_code character varying(5) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    CONSTRAINT countries_pkey PRIMARY KEY (country_id),
    CONSTRAINT countries_country_code_key UNIQUE (country_code),
    CONSTRAINT countries_country_name_key UNIQUE (country_name)
);

CREATE TABLE IF NOT EXISTS public.currencies
(
    currency_id serial NOT NULL,
    currency_code character varying(3) COLLATE pg_catalog."default" NOT NULL,
    currency_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    currency_symbol character varying(5) COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT currencies_pkey PRIMARY KEY (currency_id),
    CONSTRAINT currencies_currency_code_key UNIQUE (currency_code)
);

CREATE TABLE IF NOT EXISTS public.guide_assignments
(
    assignment_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    guide_id uuid,
    booking_id uuid,
    assignment_date date NOT NULL,
    assignment_status character varying(20) COLLATE pg_catalog."default",
    assignment_notes text COLLATE pg_catalog."default",
    CONSTRAINT guide_assignments_pkey PRIMARY KEY (assignment_id)
);

CREATE TABLE IF NOT EXISTS public.guide_specialties
(
    specialty_id serial NOT NULL,
    specialty_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    specialty_description text COLLATE pg_catalog."default",
    CONSTRAINT guide_specialties_pkey PRIMARY KEY (specialty_id),
    CONSTRAINT guide_specialties_specialty_name_key UNIQUE (specialty_name)
);

CREATE TABLE IF NOT EXISTS public.guide_specialties_mapping
(
    guide_id uuid NOT NULL,
    specialty_id integer NOT NULL,
    CONSTRAINT guide_specialties_mapping_pkey PRIMARY KEY (guide_id, specialty_id)
);

CREATE TABLE IF NOT EXISTS public.guides
(
    guide_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    license_number character varying(50) COLLATE pg_catalog."default",
    years_experience integer,
    languages_spoken text[] COLLATE pg_catalog."default",
    rating numeric(3, 2),
    is_available boolean DEFAULT true,
    daily_rate_usd numeric(8, 2),
    guide_bio text COLLATE pg_catalog."default",
    certifications text[] COLLATE pg_catalog."default",
    emergency_contact text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT guides_pkey PRIMARY KEY (guide_id),
    CONSTRAINT guides_license_number_key UNIQUE (license_number),
    CONSTRAINT guides_user_id_key UNIQUE (user_id)
);

COMMENT ON TABLE public.guides
    IS 'Safari guide profiles with specialties and availability.';

CREATE TABLE IF NOT EXISTS public.national_parks
(
    park_id serial NOT NULL,
    park_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    park_slug character varying(200) COLLATE pg_catalog."default" NOT NULL,
    park_description text COLLATE pg_catalog."default",
    park_location text COLLATE pg_catalog."default",
    size_sq_km numeric(10, 2),
    established_year integer,
    is_unesco_heritage boolean DEFAULT false,
    best_season text COLLATE pg_catalog."default",
    wildlife_highlights text COLLATE pg_catalog."default",
    image_urls text[] COLLATE pg_catalog."default",
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT national_parks_pkey PRIMARY KEY (park_id),
    CONSTRAINT national_parks_park_name_key UNIQUE (park_name),
    CONSTRAINT national_parks_park_slug_key UNIQUE (park_slug)
);

CREATE TABLE IF NOT EXISTS public.newsletter_subscribers
(
    subscriber_id serial NOT NULL,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    subscribed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT newsletter_subscribers_pkey PRIMARY KEY (subscriber_id),
    CONSTRAINT newsletter_subscribers_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    notification_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    notification_type character varying(50) COLLATE pg_catalog."default",
    notification_title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    notification_message text COLLATE pg_catalog."default" NOT NULL,
    is_read boolean DEFAULT false,
    related_entity_id character varying(100) COLLATE pg_catalog."default",
    action_url text COLLATE pg_catalog."default",
    sent_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS public.package_accommodations
(
    package_accommodation_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    package_id uuid,
    accommodation_id integer,
    night_number integer,
    room_type character varying(100) COLLATE pg_catalog."default",
    meal_plan character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT package_accommodations_pkey PRIMARY KEY (package_accommodation_id)
);

CREATE TABLE IF NOT EXISTS public.package_categories
(
    category_id serial NOT NULL,
    category_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category_slug character varying(100) COLLATE pg_catalog."default" NOT NULL,
    category_description text COLLATE pg_catalog."default",
    icon_class character varying(50) COLLATE pg_catalog."default",
    display_order integer DEFAULT 0,
    is_active boolean DEFAULT true,
    CONSTRAINT package_categories_pkey PRIMARY KEY (category_id),
    CONSTRAINT package_categories_category_name_key UNIQUE (category_name),
    CONSTRAINT package_categories_category_slug_key UNIQUE (category_slug)
);

CREATE TABLE IF NOT EXISTS public.package_destinations
(
    mapping_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    package_id uuid,
    park_id integer,
    area_id integer,
    visit_day integer,
    activities text[] COLLATE pg_catalog."default",
    is_highlight boolean DEFAULT false,
    CONSTRAINT package_destinations_pkey PRIMARY KEY (mapping_id)
);

CREATE TABLE IF NOT EXISTS public.package_itinerary
(
    itinerary_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    package_id uuid,
    day_number integer NOT NULL,
    day_title character varying(200) COLLATE pg_catalog."default" NOT NULL,
    day_description text COLLATE pg_catalog."default" NOT NULL,
    highlights text[] COLLATE pg_catalog."default",
    meals_included character varying(50) COLLATE pg_catalog."default",
    accommodation_type character varying(100) COLLATE pg_catalog."default",
    distance_km numeric(6, 2),
    max_altitude_m integer,
    image_urls text[] COLLATE pg_catalog."default",
    CONSTRAINT package_itinerary_pkey PRIMARY KEY (itinerary_id)
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens
(
    token_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    reset_token character varying(100) COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp without time zone NOT NULL,
    is_used boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (token_id),
    CONSTRAINT password_reset_tokens_reset_token_key UNIQUE (reset_token)
);

CREATE TABLE IF NOT EXISTS public.reviews
(
    review_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    booking_id uuid,
    user_id uuid,
    package_id uuid,
    rating integer NOT NULL,
    review_title character varying(200) COLLATE pg_catalog."default",
    review_comment text COLLATE pg_catalog."default" NOT NULL,
    guide_rating integer,
    accommodation_rating integer,
    food_rating integer,
    is_verified_booking boolean DEFAULT false,
    is_featured boolean DEFAULT false,
    is_approved boolean DEFAULT false,
    admin_response text COLLATE pg_catalog."default",
    helpful_votes integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT reviews_pkey PRIMARY KEY (review_id)
);

COMMENT ON TABLE public.reviews
    IS 'Customer reviews and ratings for completed safaris.';

CREATE TABLE IF NOT EXISTS public.safari_packages
(
    package_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    package_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    package_slug character varying(200) COLLATE pg_catalog."default" NOT NULL,
    category_id integer,
    short_description text COLLATE pg_catalog."default",
    detailed_description text COLLATE pg_catalog."default",
    duration_days integer NOT NULL,
    duration_nights integer NOT NULL,
    difficulty_level character varying(20) COLLATE pg_catalog."default",
    best_months character varying(100) COLLATE pg_catalog."default",
    highlights text[] COLLATE pg_catalog."default",
    included_features text[] COLLATE pg_catalog."default",
    excluded_features text[] COLLATE pg_catalog."default",
    minimum_pax integer DEFAULT 1,
    maximum_pax integer DEFAULT 12,
    child_policy text COLLATE pg_catalog."default",
    base_price_usd numeric(10, 2) NOT NULL,
    single_supplement_usd numeric(10, 2) DEFAULT 0,
    child_price_usd numeric(10, 2),
    child_age_limit integer DEFAULT 12,
    is_private boolean DEFAULT true,
    is_customizable boolean DEFAULT true,
    is_featured boolean DEFAULT false,
    is_active boolean DEFAULT true,
    meta_title character varying(200) COLLATE pg_catalog."default",
    meta_description text COLLATE pg_catalog."default",
    meta_keywords text[] COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    featured_image_url text COLLATE pg_catalog."default",
    image_urls text[] COLLATE pg_catalog."default",
    CONSTRAINT safari_packages_pkey PRIMARY KEY (package_id),
    CONSTRAINT safari_packages_package_slug_key UNIQUE (package_slug)
);

COMMENT ON TABLE public.safari_packages
    IS 'Safari package definitions including itineraries and base pricing.';

COMMENT ON COLUMN public.safari_packages.base_price_usd
    IS 'Base price per adult in USD.';

CREATE TABLE IF NOT EXISTS public.site_images
(
    id serial NOT NULL,
    filename character varying(255) COLLATE pg_catalog."default" NOT NULL,
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    path character varying(255) COLLATE pg_catalog."default" NOT NULL,
    alt_text text COLLATE pg_catalog."default",
    entity_type character varying(50) COLLATE pg_catalog."default",
    entity_id uuid,
    uploaded_by uuid,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT site_images_pkey PRIMARY KEY (id),
    CONSTRAINT site_images_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.system_settings
(
    setting_id serial NOT NULL,
    setting_key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    setting_value text COLLATE pg_catalog."default",
    setting_type character varying(50) COLLATE pg_catalog."default",
    setting_category character varying(50) COLLATE pg_catalog."default",
    setting_description text COLLATE pg_catalog."default",
    updated_by uuid,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT system_settings_pkey PRIMARY KEY (setting_id),
    CONSTRAINT system_settings_setting_key_key UNIQUE (setting_key)
);

COMMENT ON COLUMN public.system_settings.setting_type
    IS 'Data type of the setting value for proper parsing.';

CREATE TABLE IF NOT EXISTS public.user_roles
(
    role_id serial NOT NULL,
    role_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    role_description text COLLATE pg_catalog."default",
    permissions jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_roles_pkey PRIMARY KEY (role_id),
    CONSTRAINT user_roles_role_name_key UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS public.user_sessions
(
    session_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    session_token character varying(500) COLLATE pg_catalog."default" NOT NULL,
    ip_address inet,
    user_agent text COLLATE pg_catalog."default",
    expires_at timestamp without time zone NOT NULL,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_sessions_pkey PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password_hash character varying(255) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default",
    country_id integer,
    profile_image_url text COLLATE pg_catalog."default",
    role_id integer DEFAULT 1,
    email_verified boolean DEFAULT false,
    phone_verified boolean DEFAULT false,
    is_active boolean DEFAULT true,
    last_login timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    reset_token character varying(255) COLLATE pg_catalog."default",
    reset_token_expires timestamp without time zone,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email)
);

COMMENT ON TABLE public.users
    IS 'Stores user accounts with authentication data. Passwords are hashed using bcrypt.';

COMMENT ON COLUMN public.users.password_hash
    IS 'BCrypt hashed password (minimum cost 12).';

CREATE TABLE IF NOT EXISTS public.vehicles
(
    vehicle_id serial NOT NULL,
    registration_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    vehicle_make character varying(50) COLLATE pg_catalog."default" NOT NULL,
    vehicle_model character varying(50) COLLATE pg_catalog."default" NOT NULL,
    vehicle_year integer,
    vehicle_type character varying(50) COLLATE pg_catalog."default",
    passenger_capacity integer NOT NULL,
    vehicle_features text[] COLLATE pg_catalog."default",
    insurance_expiry date,
    is_available boolean DEFAULT true,
    image_urls text[] COLLATE pg_catalog."default",
    vehicle_notes text COLLATE pg_catalog."default",
    CONSTRAINT vehicles_pkey PRIMARY KEY (vehicle_id),
    CONSTRAINT vehicles_registration_number_key UNIQUE (registration_number)
);

ALTER TABLE IF EXISTS public.accommodations
    ADD CONSTRAINT accommodations_park_id_fkey FOREIGN KEY (park_id)
    REFERENCES public.national_parks (park_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_accommodations_park
    ON public.accommodations(park_id);


ALTER TABLE IF EXISTS public.accommodations
    ADD CONSTRAINT accommodations_type_id_fkey FOREIGN KEY (type_id)
    REFERENCES public.accommodation_types (type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_accommodations_type
    ON public.accommodations(type_id);


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_audit_user
    ON public.audit_logs(user_id);


ALTER TABLE IF EXISTS public.blog_posts
    ADD CONSTRAINT blog_posts_author_id_fkey FOREIGN KEY (author_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_posts_author
    ON public.blog_posts(author_id);


ALTER TABLE IF EXISTS public.blog_posts
    ADD CONSTRAINT blog_posts_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.blog_categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_posts_category
    ON public.blog_posts(category_id);


ALTER TABLE IF EXISTS public.booking_travelers
    ADD CONSTRAINT booking_travelers_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_travelers_booking
    ON public.booking_travelers(booking_id);


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_assigned_guide_id_fkey FOREIGN KEY (assigned_guide_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_assigned_vehicle_id_fkey FOREIGN KEY (assigned_vehicle_id)
    REFERENCES public.vehicles (vehicle_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_package_id_fkey FOREIGN KEY (package_id)
    REFERENCES public.safari_packages (package_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bookings_package
    ON public.bookings(package_id);


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_status_id_fkey FOREIGN KEY (status_id)
    REFERENCES public.booking_statuses (status_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bookings_status
    ON public.bookings(status_id);


ALTER TABLE IF EXISTS public.bookings
    ADD CONSTRAINT bookings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_bookings_user
    ON public.bookings(user_id);


ALTER TABLE IF EXISTS public.conservation_areas
    ADD CONSTRAINT conservation_areas_park_id_fkey FOREIGN KEY (park_id)
    REFERENCES public.national_parks (park_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_areas_park
    ON public.conservation_areas(park_id);


ALTER TABLE IF EXISTS public.contact_enquiries
    ADD CONSTRAINT contact_enquiries_assigned_to_fkey FOREIGN KEY (assigned_to)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_enquiries_assigned
    ON public.contact_enquiries(assigned_to);


ALTER TABLE IF EXISTS public.contact_enquiries
    ADD CONSTRAINT contact_enquiries_package_id_fkey FOREIGN KEY (package_id)
    REFERENCES public.safari_packages (package_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.guide_assignments
    ADD CONSTRAINT guide_assignments_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_assignments_booking
    ON public.guide_assignments(booking_id);


ALTER TABLE IF EXISTS public.guide_assignments
    ADD CONSTRAINT guide_assignments_guide_id_fkey FOREIGN KEY (guide_id)
    REFERENCES public.guides (guide_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_assignments_guide
    ON public.guide_assignments(guide_id);


ALTER TABLE IF EXISTS public.guide_specialties_mapping
    ADD CONSTRAINT guide_specialties_mapping_guide_id_fkey FOREIGN KEY (guide_id)
    REFERENCES public.guides (guide_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.guide_specialties_mapping
    ADD CONSTRAINT guide_specialties_mapping_specialty_id_fkey FOREIGN KEY (specialty_id)
    REFERENCES public.guide_specialties (specialty_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_guide_specialties
    ON public.guide_specialties_mapping(specialty_id);


ALTER TABLE IF EXISTS public.guides
    ADD CONSTRAINT guides_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS guides_user_id_key
    ON public.guides(user_id);


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_notifications_user
    ON public.notifications(user_id);


ALTER TABLE IF EXISTS public.package_accommodations
    ADD CONSTRAINT package_accommodations_accommodation_id_fkey FOREIGN KEY (accommodation_id)
    REFERENCES public.accommodations (accommodation_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_package_acc_accommodation
    ON public.package_accommodations(accommodation_id);


ALTER TABLE IF EXISTS public.package_accommodations
    ADD CONSTRAINT package_accommodations_package_id_fkey FOREIGN KEY (package_id)
    REFERENCES public.safari_packages (package_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_package_acc_package
    ON public.package_accommodations(package_id);


ALTER TABLE IF EXISTS public.package_destinations
    ADD CONSTRAINT package_destinations_area_id_fkey FOREIGN KEY (area_id)
    REFERENCES public.conservation_areas (area_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.package_destinations
    ADD CONSTRAINT package_destinations_package_id_fkey FOREIGN KEY (package_id)
    REFERENCES public.safari_packages (package_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_destinations_package
    ON public.package_destinations(package_id);


ALTER TABLE IF EXISTS public.package_destinations
    ADD CONSTRAINT package_destinations_park_id_fkey FOREIGN KEY (park_id)
    REFERENCES public.national_parks (park_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_destinations_park
    ON public.package_destinations(park_id);


ALTER TABLE IF EXISTS public.package_itinerary
    ADD CONSTRAINT package_itinerary_package_id_fkey FOREIGN KEY (package_id)
    REFERENCES public.safari_packages (package_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_itinerary_package
    ON public.package_itinerary(package_id);


ALTER TABLE IF EXISTS public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reset_tokens_user
    ON public.password_reset_tokens(user_id);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id)
    REFERENCES public.bookings (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_reviews_booking
    ON public.reviews(booking_id);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_package_id_fkey FOREIGN KEY (package_id)
    REFERENCES public.safari_packages (package_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_reviews_package
    ON public.reviews(package_id);


ALTER TABLE IF EXISTS public.reviews
    ADD CONSTRAINT reviews_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_reviews_user
    ON public.reviews(user_id);


ALTER TABLE IF EXISTS public.safari_packages
    ADD CONSTRAINT safari_packages_category_id_fkey FOREIGN KEY (category_id)
    REFERENCES public.package_categories (category_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_packages_category
    ON public.safari_packages(category_id);


ALTER TABLE IF EXISTS public.site_images
    ADD CONSTRAINT site_images_uploaded_by_fkey FOREIGN KEY (uploaded_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.system_settings
    ADD CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_sessions
    ADD CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_sessions_user
    ON public.user_sessions(user_id);


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_country_id_fkey FOREIGN KEY (country_id)
    REFERENCES public.countries (country_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.users
    ADD CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES public.user_roles (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_users_role
    ON public.users(role_id);

END;